gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  sidePanelWidth: 0.32
  nerdFontsVersion: 3
  filterMode: fuzzy
  theme:
    selectedLineBgColor:
      - bold
      - reverse
      # - '#404040'
  commitHashLength: 5

  spinner:
    frames:
      # https://andreichiril.neocities.org/braille
      # - '⢿'
      # - '⣻'
      # - '⣽'
      # - '⣾'
      # - '⣷'
      # - '⣯'
      # - '⣟'
      # - '⡿'
      #
      - '⣏⣀ '
      - '⣏⡁ '
      - '⣏⠉ '
      - '⡏⠙ '
      - '⠏⠹ '
      - '⠋⢹ '
      - '⠉⣹ '
      - '⢈⣹ '
      - '⣀⣹ '
      - '⣄⣸ '
      - '⣆⣰ '
      - '⣇⣠ '

git:
  pagers:
    - pager: delta --config $HOME/.config/delta/.gitconfig --paging=never --features='unified-view'
    - pager: delta --config $HOME/.config/delta/.gitconfig --paging=never --features='split-view'
    # - externalDiffCommand: difft
    # - useExternalDiffGitConfig: true

notARepository: skip
promptToReturnFromSubprocess: false









