gui:
  sidePanelWidth: 0.34
  nerdFontsVersion: 3
  theme:
    selectedLineBgColor:
      - bold
      - '#404040'
  commitHashLength: 5

  spinner:
    frames:
      # https://andreichiril.neocities.org/braille
      # - '⢿'
      # - '⣻'
      # - '⣽'
      # - '⣾'
      # - '⣷'
      # - '⣯'
      # - '⣟'
      # - '⡿'
      #
      - '⣏⣀ '
      - '⣏⡁ '
      - '⣏⠉ '
      - '⡏⠙ '
      - '⠏⠹ '
      - '⠋⢹ '
      - '⠉⣹ '
      - '⢈⣹ '
      - '⣀⣹ '
      - '⣄⣸ '
      - '⣆⣰ '
      - '⣇⣠ '

git:
  pagers:
    - pager: delta --config $HOME/.config/delta/.gitconfig --features=for-lazygit
    - pager: delta --config $HOME/.config/delta/.gitconfig --features=for-lazygit-side-by-side
    # - externalDiffCommand: difft
    # - useExternalDiffGitConfig: true

notARepository: skip
promptToReturnFromSubprocess: false








