settings:
  tailMode: 5000
  updateInterval: 5
  disableAutoUpdate: false
  disableColor: false
  disableMouse: false
  disableTimestamp: false
  onlyStream: false

  disableFastMode: false
